name: build

on:
  workflow_dispatch:

concurrency:
  group: build-${{ github.head_ref }}
  cancel-in-progress: true

env:
  PYTHON_VERSION: '3.13'
  COINCURVE_IGNORE_SYSTEM_LIB: 'ON'
  COINCURVE_SECP256K1_STATIC: 'ON'
  COINCURVE_CROSS_HOST: ''
  CIBW_BUILD: 'cp314-*'
  CIBW_ENVIRONMENT_PASS_LINUX: >
    COINCURVE_IGNORE_SYSTEM_LIB
    COINCURVE_SECP256K1_STATIC
    COINCURVE_CROSS_HOST
  CIBW_BEFORE_ALL_MACOS: ./.github/scripts/install-macos-build-deps.sh
  CIBW_TEST_REQUIRES: pytest
  CIBW_TEST_COMMAND: >
    python -c
    "from coincurve import PrivateKey;
    a=PrivateKey();
    b=PrivateKey();
    assert a.ecdh(b.public_key.format())==b.ecdh(a.public_key.format())
    " &&
    python -m pytest {project}
  CIBW_SKIP: >
      pp*

jobs:
  linux-wheels-x86_64:
    name: Build Linux wheels for x86-64
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5

    - name: Build wheels
      uses: pypa/cibuildwheel@v4.1.0

    - uses: actions/upload-artifact@v4
      with:
        name: artifact-linux-wheels-x86_64
        path: wheelhouse/*.whl
        if-no-files-found: error

  macos-wheels-x86_64:
    name: Build macOS wheels for x86-64
    runs-on: macos-15-intel

    steps:
    - uses: actions/checkout@v5

    - name: Build wheels
      uses: pypa/cibuildwheel@v4.1.0
      env:
        CIBW_ARCHS_MACOS: x86_64
        CIBW_SKIP: "cp314t-*"
        MACOSX_DEPLOYMENT_TARGET: 10.13

    - uses: actions/upload-artifact@v4
      with:
        name: artifact-macos-wheels-x86_64
        path: wheelhouse/*.whl
        if-no-files-found: error

  macos-wheels-arm64:
    name: Build macOS wheels for ARM64
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v5

    - name: Build wheels
      uses: pypa/cibuildwheel@v4.1.0

    - uses: actions/upload-artifact@v4
      with:
        name: artifact-macos-wheels-arm64
        path: wheelhouse/*.whl
        if-no-files-found: error

  windows-wheels-x86_64:
    name: Build Windows wheels for x86-64
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v5

    - uses: actions/setup-python@v6
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Build wheels
      uses: pypa/cibuildwheel@v4.1.0
      env:
        CIBW_ARCHS_WINDOWS: 'AMD64'
        CIBW_BEFORE_ALL: choco install -y --no-progress --no-color cmake>=3.28

    - uses: actions/upload-artifact@v4
      with:
        name: artifact-windows-wheels-x86_64
        path: wheelhouse/*.whl
        if-no-files-found: error

  sdist:
    name: Build source distribution
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5

    - name: Install build dependencies
      run: python -m pip install build

    - name: Build source distribution
      run: python -m build --sdist

    - uses: actions/upload-artifact@v4
      with:
        name: artifact-sdist
        path: dist/*
        if-no-files-found: error

  linux-wheels-arm64:
    name: Build Linux wheels for ARM64
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
      with:
        platforms: arm64

    - name: Build wheels
      uses: pypa/cibuildwheel@v4.1.0
      env:
        CIBW_ARCHS_LINUX: aarch64

    - uses: actions/upload-artifact@v4
      with:
        name: artifact-linux-wheels-arm64
        path: wheelhouse/*.whl
        if-no-files-found: error

  publish:
    name: Create GitHub release
    needs:
    - linux-wheels-x86_64
    - macos-wheels-x86_64
    - macos-wheels-arm64
    - windows-wheels-x86_64
    - sdist
    - linux-wheels-arm64
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - uses: actions/download-artifact@v5
      with:
        pattern: artifact-*
        merge-multiple: true
        path: dist
    - run: ls -l dist

    - name: Create GitHub release with wheels
      uses: softprops/action-gh-release@v2
      with:
        tag_name: v21.0.0-cp314-fix
        files: dist/*
